# Dockerfile.react

# Base build
FROM node:lts as build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

# Development environment
FROM build as react-dev

WORKDIR /app/src/public/frontend

# Exponha a porta 3000 para o frontend
EXPOSE 3000

# Inicie o servidor em desenvolvimento
CMD ["npm", "start", "--", "--host", "0.0.0.0"]
