version: '3.8'
services:
  node-app:
    build:
      context: ..
      dockerfile: Dockerfile.backend
      target: dev
    volumes:
      - ../src:/app/src:rw  # Mount src as read-write for backend development
      - ../src/public/frontend:/app/src/public/frontend:rw  # Mount frontend folder for shared access
      - /app/node_modules  # Ignora node_modules do host
    ports:
      - 5000:5000
    env_file:
      - ../env/backend.env
    depends_on:
      - mongodb-dev
    networks:
      - backend
      - frontend-backend

  react-dev:
    build:
      context: ..
      dockerfile: Dockerfile.react
    volumes:
      - ../src:/app/src:rw                # Mount src as read-write for React development
      - ../src/public/frontend:/app/src/public/frontend:rw  # Mount frontend folder
      - /app/node_modules  # Ignora node_modules do host
    ports:
      - 3000:3000
    networks:
      - frontend
      - frontend-backend
    depends_on:
      - node-app
    environment:
      - NODE_ENV=development


  mongodb-dev:
    image: "mongo"
    container_name: mongodb-dev
    ports:
      - 27017:27017
    volumes:
      - data-dev:/data/db:rw
    env_file:
      - ../env/mongodb.env
    networks:
      - backend

volumes:
  data-dev:

networks:
  backend:
  frontend:
  frontend-backend:
    driver: bridge